apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vaultwarden-secrets
  namespace: vaultwarden
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: vaultwarden-secrets
    creationPolicy: Owner
  data:
    - secretKey: db_url
      remoteRef:
        key: mfo/private/vaultwarden/secrets
        property: db_url
    - secretKey: admin_token
      remoteRef:
        key: mfo/private/vaultwarden/secrets
        property: admin_token