apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: foursquare-bot-secrets
  namespace: mfo-bots
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: foursquare-bot-secrets
    creationPolicy: Owner
  data:
    - secretKey: FIREBASE_BASE64_CREDS
      remoteRef:
        key: mfo/private/bots/env-vars
        property: FIREBASE_BASE64_CREDS
    - secretKey: TZ
      remoteRef:
        key: mfo/private/bots/env-vars
        property: TZ
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-secret
  namespace: mfo-bots
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: ghcr-secret
    creationPolicy: Owner
  data:
    - secretKey: docker-server
      remoteRef:
        key: ghcr
        property: docker-server
    - secretKey: docker-username
      remoteRef:
        key: ghcr
        property: docker-username
    - secretKey: docker-password
      remoteRef:
        key: ghcr
        property: docker-password
    - secretKey: docker-email
      remoteRef:
        key: ghcr
        property: docker-email

