apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: foursquare-bot-secrets
  namespace: f6sny
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: foursquare-bot-secrets
    creationPolicy: Owner
  data:
    - secretKey: FIREBASE_BASE64_CREDS
      remoteRef:
        key: mfo/private/bots/env-vars
        property: FIREBASE_BASE64_CREDS
    - secretKey: TZ
      remoteRef:
        key: mfo/private/bots/env-vars
        property: TZ
