apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitch-bot
  labels:
    app: twitch-bot
  namespace: mfo-bots
spec:
  replicas: 1  # Start with 1 replica since this seems to be a stateful app
  selector:
    matchLabels:
      app: twitch-bot
  template:
    metadata:
      labels:
        app: twitch-bot
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: twitch-bot
        image: ghcr.io/flowdegree/js_twitch_bot:latest  # Replace with your actual image
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        envFrom:
          - secretRef:
              name: twitch-bot-secrets