apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: twitch-bot-secrets
  namespace: mfo-bots
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: twitch-bot-secrets
    creationPolicy: Owner
  data:
    - secretKey: FIREBASE_BASE64_CREDS
      remoteRef:
        key: mfo/private/bots/env-vars
        property: FIREBASE_BASE64_CREDS

    - secretKey: TZ
      remoteRef:
        key: mfo/private/bots/env-vars
        property: TZ

    - secretKey: TWITCH_CLIENT_ID 
      remoteRef:
        key: mfo/private/bots/twitch
        property: TWITCH_CLIENT_ID

    - secretKey: TWITCH_CLIENT_SECRET
      remoteRef:
        key: mfo/private/bots/twitch
        property: TWITCH_CLIENT_SECRET