apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linear-discord-bot-secrets
  namespace: mfo-bots
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: linear-discord-bot-secrets
    creationPolicy: Owner
  data:
    - secretKey: DISCORD_WEBHOOK_URL
      remoteRef:
        key: mfo/private/bots/discord
        property: DISCORD_WEBHOOK_URL
    - secretKey: TZ
      remoteRef:
        key: mfo/private/bots/env-vars
        property: TZ