apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vaultwarden-db-secret
  namespace: vaultwarden
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: vaultwarden-db-secret
    creationPolicy: Owner
  data:
    - secretKey: url
      remoteRef:
        key: vaultwarden_db_secret
        property: url
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vaultwarden-admin-token
  namespace: vaultwarden
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: vaultwarden-admin-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: vaultwarden_admin_token
        property: token
