apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-bot-secrets
  namespace: mfo-bots
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: github-bot-secrets
    creationPolicy: Owner
  data:
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: mfo/private/bots/github
        property: GITHUB_TOKEN
    - secretKey: TZ
      remoteRef:
        key: mfo/private/bots/env-vars
        property: TZ